spring:
  application:
    name: StockApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stockdb
  datasource:
    url: jdbc:mysql://localhost:3306/lab_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: zensar
      password: zensar123    
server:
  port: 9001


  
management:
  endpoints:
    web:
      base-path: /stockapp
      exposure:
        include:
        - "*" 
        exclude:
        - "beans"
      
        
  endpoint:
    health:
      enabled: true
    shutdown:
      enabled: true
